<a href="https://colab.research.google.com/github/YASHYOGESHAHIRE/01-equal-weights/blob/main/Equal_Weights.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Equal Weights

In [ ]:
import pandas as pd
import numpy as np
import  yfinance as yf
import math

In [ ]:
pip install yfinance

Requirement already satisfied: yfinance in /usr/local/lib/python3.12/dist-packages (0.2.66)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.0.2)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.32.4)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.0.13)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.9.6)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.4.7)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.0.6)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.13.5)
Requirement already satisfied: curl_cffi>=0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.15.0)
Requirement already satisfied: protobuf>=3.19.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (5.29.6)
Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (15.0.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2026.5.20)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (13.9.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2026.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.15)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (2.5.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0.0->curl_cffi>=0.7->yfinance) (3.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->curl_cffi>=0.7->yfinance) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->curl_cffi>=0.7->yfinance) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.7->yfinance) (0.1.2)

Load the Stock List

In [ ]:
tickers = pd.read_csv('/content/top_50_indian_stocks.csv')
tickers.head()

         Ticker               Company Name
0   RELIANCE.NS        Reliance Industries
1        TCS.NS  Tata Consultancy Services
2   HDFCBANK.NS                  HDFC Bank
3       INFY.NS                    Infosys
4  ICICIBANK.NS                 ICICI Bank

In [ ]:
import yfinance as yf
import pandas as pd

def fetch_market_cap(ticker_list):

    data = yf.download(
        ticker_list,
        period='1d',
        group_by='ticker',
        auto_adjust=False
    )

    stocks_data = []

    for ticker in ticker_list:

        try:
            latest_price = data[ticker]['Close'].iloc[-1]
        except:
            latest_price = None

        try:
            market_cap = yf.Ticker(ticker).info.get("marketCap", "N/A")
        except:
            market_cap = "N/A"

        stocks_data.append({
            "Ticker": ticker,
            "Market Cap": market_cap,
            "Latest Price": latest_price
        })

    stocks_df = pd.DataFrame(stocks_data)

    return stocks_df


tickers_list = tickers["Ticker"].tolist()

df = fetch_market_cap(tickers_list)

print(df)

[*********************100%***********************]  50 of 50 completed
ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['TATAMOTORS.NS']: YFPricesMissingError('possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")')
ERROR:yfinance:HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TATAMOTORS.NS"}}}

           Ticker      Market Cap  Latest Price
0     RELIANCE.NS  17470422253568   1291.000000
1          TCS.NS   7955811926016   2198.899902
2     HDFCBANK.NS  11501749403648    747.049988
3         INFY.NS   4848204382208   1197.500000
4    ICICIBANK.NS   9048799838208   1262.099976
5   HINDUNILVR.NS   4984657674240   2121.500000
6         SBIN.NS   9024774864896    977.700012
7   BAJFINANCE.NS   5530179338240    889.400024
8   BHARTIARTL.NS  10953684942848   1798.199951
9          ITC.NS   3517021945856    280.700012
10   KOTAKBANK.NS   3754293460992    377.450012
11    ADANIENT.NS   4182092546048   3048.199951
12          LT.NS   5438291574784   3953.199951
13     HCLTECH.NS   3124216725504   1154.699951
14  ASIANPAINT.NS   2575589441536   2686.699951
15    AXISBANK.NS   3956924743680   1272.300049
16   SUNPHARMA.NS   4276094500864   1782.199951
17       WIPRO.NS   2080973651968    198.369995
18  ULTRACEMCO.NS   3209978970112  10912.000000
19    HDFCLIFE.NS   1241158647808    575.299988
20        ONGC.NS   3330628911104    264.750000
21        NTPC.NS   3506799378432    361.649994
22   POWERGRID.NS   2656717504512    285.649994
23  TATAMOTORS.NS             N/A           NaN
24  INDUSINDBK.NS    704959283200    904.799988
25  ADANIGREEN.NS   2513096671232   1525.699951
26       TITAN.NS   3778990309376   4260.200195
27    DIVISLAB.NS   1758198366208   6623.000000
28       TECHM.NS   1313963376640   1483.500000
29      MARUTI.NS   4102953369600  13050.000000
30   COALINDIA.NS   2910656659456    472.299988
31        BPCL.NS   1260412600320    295.000000
32    JSWSTEEL.NS   3133773185024   1284.000000
33     DRREDDY.NS   1064039153664   1278.199951
34  BAJAJFINSV.NS   2722579349504   1703.199951
35  ADANIPORTS.NS   4202881875968   1824.199951
36       CIPLA.NS   1131970953216   1401.300049
37   BRITANNIA.NS   1233366024192   5120.500000
38     HAVELLS.NS    721658970112   1150.500000
39    SHREECEM.NS    869004804096  24085.000000
40      GRASIM.NS   2093994082304   3087.699951
41   TATASTEEL.NS   2578804113408    206.770004
42  HEROMOTOCO.NS    967449378816   4835.000000
43         M&M.NS   3650917498880   3040.500000
44   EICHERMOT.NS   1940697645056   7070.000000
45         IOC.NS   1952402374656    138.259995
46     SBICARD.NS    561068834816    589.599976
47  PIDILITIND.NS   1502847041536   1476.599976
48       DMART.NS   2702697299968   4144.200195
49     HDFCAMC.NS   1069875593216   2495.899902

In [ ]:
df["Market Cap"] = pd.to_numeric(df["Market Cap"], errors="coerce")

df = df.sort_values(by="Market Cap", ascending=False)

df

           Ticker    Market Cap  Latest Price
0     RELIANCE.NS  1.747042e+13   1291.000000
2     HDFCBANK.NS  1.150175e+13    747.049988
8   BHARTIARTL.NS  1.095368e+13   1798.199951
4    ICICIBANK.NS  9.048800e+12   1262.099976
6         SBIN.NS  9.024775e+12    977.700012
1          TCS.NS  7.955812e+12   2198.899902
7   BAJFINANCE.NS  5.530179e+12    889.400024
12          LT.NS  5.438292e+12   3953.199951
5   HINDUNILVR.NS  4.984658e+12   2121.500000
3         INFY.NS  4.848204e+12   1197.500000
16   SUNPHARMA.NS  4.276095e+12   1782.199951
35  ADANIPORTS.NS  4.202882e+12   1824.199951
11    ADANIENT.NS  4.182093e+12   3048.199951
29      MARUTI.NS  4.102953e+12  13050.000000
15    AXISBANK.NS  3.956925e+12   1272.300049
26       TITAN.NS  3.778990e+12   4260.200195
10   KOTAKBANK.NS  3.754293e+12    377.450012
43         M&M.NS  3.650917e+12   3040.500000
9          ITC.NS  3.517022e+12    280.700012
21        NTPC.NS  3.506799e+12    361.649994
20        ONGC.NS  3.330629e+12    264.750000
18  ULTRACEMCO.NS  3.209979e+12  10912.000000
32    JSWSTEEL.NS  3.133773e+12   1284.000000
13     HCLTECH.NS  3.124217e+12   1154.699951
30   COALINDIA.NS  2.910657e+12    472.299988
34  BAJAJFINSV.NS  2.722579e+12   1703.199951
48       DMART.NS  2.702697e+12   4144.200195
22   POWERGRID.NS  2.656718e+12    285.649994
41   TATASTEEL.NS  2.578804e+12    206.770004
14  ASIANPAINT.NS  2.575589e+12   2686.699951
25  ADANIGREEN.NS  2.513097e+12   1525.699951
40      GRASIM.NS  2.093994e+12   3087.699951
17       WIPRO.NS  2.080974e+12    198.369995
45         IOC.NS  1.952402e+12    138.259995
44   EICHERMOT.NS  1.940698e+12   7070.000000
27    DIVISLAB.NS  1.758198e+12   6623.000000
47  PIDILITIND.NS  1.502847e+12   1476.599976
28       TECHM.NS  1.313963e+12   1483.500000
31        BPCL.NS  1.260413e+12    295.000000
19    HDFCLIFE.NS  1.241159e+12    575.299988
37   BRITANNIA.NS  1.233366e+12   5120.500000
36       CIPLA.NS  1.131971e+12   1401.300049
49     HDFCAMC.NS  1.069876e+12   2495.899902
33     DRREDDY.NS  1.064039e+12   1278.199951
42  HEROMOTOCO.NS  9.674494e+11   4835.000000
39    SHREECEM.NS  8.690048e+11  24085.000000
38     HAVELLS.NS  7.216590e+11   1150.500000
24  INDUSINDBK.NS  7.049593e+11    904.799988
46     SBICARD.NS  5.610688e+11    589.599976
23  TATAMOTORS.NS           NaN           NaN

In [ ]:
print(df)

           Ticker    Market Cap  Latest Price
0     RELIANCE.NS  1.747042e+13   1291.000000
2     HDFCBANK.NS  1.150175e+13    747.049988
8   BHARTIARTL.NS  1.095368e+13   1798.199951
4    ICICIBANK.NS  9.048800e+12   1262.099976
6         SBIN.NS  9.024775e+12    977.700012
1          TCS.NS  7.955812e+12   2198.899902
7   BAJFINANCE.NS  5.530179e+12    889.400024
12          LT.NS  5.438292e+12   3953.199951
5   HINDUNILVR.NS  4.984658e+12   2121.500000
3         INFY.NS  4.848204e+12   1197.500000
16   SUNPHARMA.NS  4.276095e+12   1782.199951
35  ADANIPORTS.NS  4.202882e+12   1824.199951
11    ADANIENT.NS  4.182093e+12   3048.199951
29      MARUTI.NS  4.102953e+12  13050.000000
15    AXISBANK.NS  3.956925e+12   1272.300049
26       TITAN.NS  3.778990e+12   4260.200195
10   KOTAKBANK.NS  3.754293e+12    377.450012
43         M&M.NS  3.650917e+12   3040.500000
9          ITC.NS  3.517022e+12    280.700012
21        NTPC.NS  3.506799e+12    361.649994
20        ONGC.NS  3.330629e+12    264.750000
18  ULTRACEMCO.NS  3.209979e+12  10912.000000
32    JSWSTEEL.NS  3.133773e+12   1284.000000
13     HCLTECH.NS  3.124217e+12   1154.699951
30   COALINDIA.NS  2.910657e+12    472.299988
34  BAJAJFINSV.NS  2.722579e+12   1703.199951
48       DMART.NS  2.702697e+12   4144.200195
22   POWERGRID.NS  2.656718e+12    285.649994
41   TATASTEEL.NS  2.578804e+12    206.770004
14  ASIANPAINT.NS  2.575589e+12   2686.699951
25  ADANIGREEN.NS  2.513097e+12   1525.699951
40      GRASIM.NS  2.093994e+12   3087.699951
17       WIPRO.NS  2.080974e+12    198.369995
45         IOC.NS  1.952402e+12    138.259995
44   EICHERMOT.NS  1.940698e+12   7070.000000
27    DIVISLAB.NS  1.758198e+12   6623.000000
47  PIDILITIND.NS  1.502847e+12   1476.599976
28       TECHM.NS  1.313963e+12   1483.500000
31        BPCL.NS  1.260413e+12    295.000000
19    HDFCLIFE.NS  1.241159e+12    575.299988
37   BRITANNIA.NS  1.233366e+12   5120.500000
36       CIPLA.NS  1.131971e+12   1401.300049
49     HDFCAMC.NS  1.069876e+12   2495.899902
33     DRREDDY.NS  1.064039e+12   1278.199951
42  HEROMOTOCO.NS  9.674494e+11   4835.000000
39    SHREECEM.NS  8.690048e+11  24085.000000
38     HAVELLS.NS  7.216590e+11   1150.500000
24  INDUSINDBK.NS  7.049593e+11    904.799988
46     SBICARD.NS  5.610688e+11    589.599976
23  TATAMOTORS.NS           NaN           NaN

Taking Top 10 Stocks as per the Makert Cap

In [ ]:
df = df.head(10)

df.reset_index(inplace=True,drop=True)

df

   index         Ticker    Market Cap  Latest Price
0      0    RELIANCE.NS  1.747042e+13   1291.000000
1      2    HDFCBANK.NS  1.150175e+13    747.049988
2      8  BHARTIARTL.NS  1.095368e+13   1798.199951
3      4   ICICIBANK.NS  9.048800e+12   1262.099976
4      6        SBIN.NS  9.024775e+12    977.700012
5      1         TCS.NS  7.955812e+12   2198.899902
6      7  BAJFINANCE.NS  5.530179e+12    889.400024
7     12          LT.NS  5.438292e+12   3953.199951
8      5  HINDUNILVR.NS  4.984658e+12   2121.500000
9      3        INFY.NS  4.848204e+12   1197.500000

In [ ]:
portfolio_size = int(input("Enter the amount you want to invest : "))
position_size =  portfolio_size / len(df.index)

Enter the amount you want to invest : 100000

In [ ]:
print(position_size)

10000.0

In [ ]:
df['Number of Shares to buy'] = df['Latest Price'].apply(lambda price: math.floor(
    position_size/price

))

In [ ]:
df

   index         Ticker    Market Cap  Latest Price  Number of Shares to buy
0      0    RELIANCE.NS  1.747042e+13   1291.000000                        7
1      2    HDFCBANK.NS  1.150175e+13    747.049988                       13
2      8  BHARTIARTL.NS  1.095368e+13   1798.199951                        5
3      4   ICICIBANK.NS  9.048800e+12   1262.099976                        7
4      6        SBIN.NS  9.024775e+12    977.700012                       10
5      1         TCS.NS  7.955812e+12   2198.899902                        4
6      7  BAJFINANCE.NS  5.530179e+12    889.400024                       11
7     12          LT.NS  5.438292e+12   3953.199951                        2
8      5  HINDUNILVR.NS  4.984658e+12   2121.500000                        4
9      3        INFY.NS  4.848204e+12   1197.500000                        8